[package]
name = "seer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "^4.0"
lazy_static = "1.5.0"
regex = "1.5"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.2"
predicates = "3.1.3"

[lib]
name = "seer"
path = "src/lib.rs"

[[bin]]
name = "seer"
path = "src/main.rs"
